name: radio_chacaltaya
description: App de radio con panel admin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.10.3

  # Gestión de estado
  provider: ^6.1.2

  # Reproductor de audio/video
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  video_player: ^2.10.0
  carousel_slider: ^5.1.1  # última estable (todavía necesaria la fijación)

  # UI
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  fluentui_system_icons: ^1.1.273
  url_launcher: ^6.3.2
  audio_session: ^0.2.2

  # Utilidades
  intl: ^0.20.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/Logo.png
    - assets/Icon/instagram.png
    - assets/Icon/facebook.png
    - assets/Icon/tiktok.png
    - assets/img/radio.png
    - assets/Icon/whassapp.png
    - assets/img/img-radio.png

dependency_overrides:
  # Workaround para conflicto con CarouselController en Flutter
  carousel_slider: ^5.1.1
